# Generated by Django 3.1.7 on 2021-03-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('ubicacion', models.TextField(max_length=255)),
                ('imagen', models.ImageField(upload_to='caidas/')),
            ],
        ),
    ]
