# Generated by Django 3.1.7 on 2021-04-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.TextField(default='0000000000', max_length=10)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(default='', max_length=255, unique=True)),
                ('telefono', models.TextField(default='', max_length=15, unique=True)),
                ('clave', models.TextField(max_length=30)),
                ('tipo', models.TextField(default='familiar', max_length=10)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.usuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Caida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('presicion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('imagen', models.ImageField(upload_to='monitor/caidas')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monitor.paciente')),
            ],
        ),
    ]
