# Generated by Django 3.1.7 on 2021-04-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_contacto_persona_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.persona'),
        ),
    ]
