# Generated by Django 3.1.7 on 2021-04-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210414_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caida',
            old_name='presicion',
            new_name='precision',
        ),
    ]
