# Generated by Django 3.1.7 on 2021-04-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.TextField(max_length=30),
        ),
    ]
