# Generated by Django 3.1.7 on 2021-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20210408_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
