# Generated by Django 3.1.7 on 2021-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20210408_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='persona',
        ),
        migrations.AlterField(
            model_name='caida',
            name='imagen',
            field=models.ImageField(upload_to='monitor/caidas'),
        ),
    ]
