# Generated by Django 3.1.7 on 2021-04-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20210409_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='familiar',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='monitor.persona'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='monitor.persona'),
        ),
    ]
