# Generated by Django 3.1.7 on 2021-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20210409_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ubicacion',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
