# Generated by Django 3.1.7 on 2021-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20210410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ubicacion',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
