# Generated by Django 3.1.7 on 2021-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20210410_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ubicacion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
