# Generated by Django 3.1.7 on 2021-04-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20210410_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='familiar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.persona'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.persona')),
            ],
        ),
        migrations.AddField(
            model_name='caida',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monitor.paciente'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.paciente'),
        ),
    ]
