# Generated by Django 3.1.7 on 2021-04-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20210410_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caida',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='caida',
            name='presicion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
