# Generated by Django 3.1.7 on 2021-04-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20210410_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.TextField(default='0000000000', max_length=10),
        ),
    ]
