# Generated by Django 3.1.7 on 2021-04-11 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_persona_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.paciente'),
        ),
    ]
