# Generated by Django 3.1.7 on 2021-04-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_auto_20210411_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.paciente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.TextField(default='familiar', max_length=10),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.telefono'),
        ),
    ]
