# Generated by Django 3.1.7 on 2021-04-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_auto_20210412_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.TextField(default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='familiar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.usuario'),
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
