# Generated by Django 3.1.7 on 2021-04-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_auto_20210412_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.TextField(max_length=15, null=True, unique=True),
        ),
    ]
