# Generated by Django 3.1.7 on 2021-04-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_auto_20210412_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.TextField(default='', max_length=15),
        ),
    ]
